# Generated by Django 4.1.5 on 2023-02-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listing",
            new_name="Listings",
        ),
    ]
