# Generated by Django 4.1.5 on 2023-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_rename_listing_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="user",
            field=models.CharField(default="god", max_length=64),
        ),
    ]
