# Generated by Django 4.1.5 on 2023-02-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listings_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="user",
        ),
    ]
