# Generated by Django 4.1.5 on 2023-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_listings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="id",
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
