# Generated by Django 4.1.5 on 2023-02-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
            preserve_default=False,
        ),
    ]
