# Generated by Django 4.1.5 on 2023-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_comments_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="listing",
        ),
        migrations.AddField(
            model_name="comments",
            name="listing_id",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
