# Generated by Django 4.2.1 on 2023-06-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_listings_closed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listings",
            old_name="photo_url",
            new_name="image_url",
        ),
    ]
