# Generated by Django 4.2.1 on 2023-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_listings_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fhesolutions.com.pk%2Fwp-content%2Fuploads%2F2019%2F01%2Fpicture-not-available.jpg&f=1&nofb=1&ipt=1af2f84142eef942dba6c862905aa06c0b03301dad11cfe9234b6958cb63f132&ipo=images",
                max_length=500,
                null=True,
            ),
        ),
    ]
