# Generated by Django 4.2.1 on 2023-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_alter_listings_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
