# Generated by Django 4.2.1 on 2023-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_alter_listings_image_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
